Adding Example UML to SEP 055 and Fixing Typos
SynBioDex/SEPs pull request #116
Opened 2022-02-09 16:23 UTC by nroehner

These changes should not change any of the best practices described in SEP 055 and rather should clarify them.

2022-02-09 21:14 UTC, jakebeal requested changes
Looking good; just a few changes to request.

2022-02-10 20:06 UTC, jakebeal commented
OK, just waiting for the markdown file updates now.

2022-02-17 00:32 UTC, nroehner commented on sep_055.md
> +An assembled part within a composite part SHOULD be represented by including a `feature` in the composite `Component` that is a `SubComponent` with an `instanceOf` property that links to the `Compone
Reverted to previous phrasing.

2022-02-17 00:33 UTC, nroehner commented on sep_055.md
> +**Figure 2:** Composite part example UML diagram with `Locations`. SO:0001953 stands for restriction_enzyme_assembly_scar and SO:0000139 stands for ribosome_entry_site.
Example UML diagrams now have narrative description.

2022-02-17 00:34 UTC, nroehner commented
I think this should be good to merge unless you meant something else by markdown file updates.

2022-02-17 16:07 UTC, merged